name: Combine Jobs

on:
  pull_request:
    branches:
      - main

permissions:
  actions: none

jobs:
  llcppg-combine:
    name: Combine Platform
    needs: [llcppg-generate]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository.
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Combine
        uses: actions/download-artifact@v4
        with:
          name: llcppg-production
      - name: List all files
        run: |
          ls
