name: Continuous Integration

on:
  label:
    types: [created]
  

jobs:
  test-label-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        run: |
          echo {{github.event.label.name}}

